存储光交管理系统/manager/ceshi/urls.py
from san import views
from django.conf.urls import url
from django.contrib import admin
from ceshi import views
from django.conf import settings
# from django.conf.urls.static import static
from django.conf.urls import include
urlpatterns = [
    url(r"search/",views.search),
    url(r"search1/",views.search1),
    url(r"fenye/",views.fenye),
    url(r"test/",views.Testtubiao)
]

# static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

存储光交管理系统/manager/manager/urls.py
from san import views
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
# from django.conf.urls.static import static
from django.conf.urls import include
from ceshi.views import fenye
import work
# from script.upload import upload_image
from django.views.decorators.cache import cache_page
import xadmin
urlpatterns = [
    url(r'^admin/',xadmin.site.urls),
    url(r"^$",views.index,name = "index"),
    url(r"index",views.index,name = "index"),
    url(r"^log_mess/(?P<log_id>[0-9]+)/",views.log_xiangxi,name = "log_mess"),
    url(r"update/(?P<update_id>[0-9]+)/",views.logupdate,name = "logupdate"),
    url(r"sanlink/$",views.Sanlink,name="sanlink"),
    url(r"storage/",views.Storges,name="storge"),
    url(r"caiji/",views.Caiji,name="Caiji"),
    url(r"yewu/",cache_page(60 * 90)(views.Yewu),name="yewu"),
    url(r"alert/",views.Alert,name="alert"),
    url(r"ceshi/",include('ceshi.urls')),
    url(r"fenye/",fenye),
    url(r"^sanupdateall/",views.Sanupdateall,name="sanupdateall"),
    url(r"^san_huitu_update/",views.San_huitu_update,name="san_huitu_update"),
    url(r"^san_liuliang_im/",views.san_liuliang_im,name="san_liuliang_im"),
    url(r"^caiji_san_port/",views.Caiji_san_port,name="caiji_san_port"),
    url(r"^san_err_get_shuju/",views.San_err_get_shuju,name="san_err_get_shuju"),
    url(r"^host_search_ajax/",views.host_search_ajax,name="host_search_ajax"),
    url(r"^san_sel_update_ajax/",views.San_sel_update_ajax,name="san_sel_update_ajax"),
    url(r"sanlink/sanmess/(?P<sanmess_id>[0-9]*)",cache_page(60 * 15)(views.Sanmess),name="sanmess"),
    url(r"sancompall/$",views.Sancompall,name="sancompall"),
    url(r"^host/$",views.Host,name="host"),
    url(r"^Addhost/$", views.Addhost, name="addhost"),
    url(r"^addhost_ajax/$",views.addhost_ajax,name="addhost_ajax"),
    url(r"storagemess/(?P<storage_id>[0-9]*)",cache_page(60 * 15)(views.Storagemess),name="storagemess"),
    url(r"^storage_log/",views.Storages_log,name= "storages_log"),
    url(r"san_log/",views.San_log,name= "san_log"),
    url(r"san_port_tables/",views.San_port_tables,name= "san_port_tables"),
    url(r"san_port_err_tables/",views.San_port_err_tables,name= "san_port_err_tables"),
    url(r"san_liuliang_import/",views.san_liuliang_import,name= "san_liuliang_import"),
    url(r"^logout/$",views.Logout,name= "logout"),
    url(r"^login/$",views.Auto_login,name= "auto_login"),
    url(r"login_ajax/",views.Login_ajax,name= "login_ajax"),
    url(r"search_messages/",views.Search_messages,name= "search_messages"),
    url("^work",include('work.urls')),
    url("^storages",include('storagedata.urls')),
    # url(r'^admin/uploads/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
    url(r"^hot_wwn/",cache_page(60 * 150)(views.Hot_wwn),name= "Hot_wwn"),
    # url(r"^uploads/(?P<path>.*)$", views.static.serve, {"document_root": settings.MEDIA_ROOT, }),
]

# static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

存储光交管理系统/manager/work/urls.py
from work import views
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
# from django.conf.urls.static import static
from django.conf.urls import include
import work
urlpatterns = [
    url(r'/faults/',views.Faults,name="faults_manager"),
    url(r'/work_manager/',views.Work_manager,name="work_manager"),
    url(r'/work_work_ajax/',views.Work_work_ajax,name="work_work_ajax"),
    url(r'/work_modfiy/',views.Work_modfiy,name="work_modfiy"),
    url(r'/work_upadte_ajax/',views.Work_upadte_ajax,name="work_upadte_ajax"),
]

# static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

存储光交管理系统/manager/ceshi/models.py
# -*- coding: utf-8 -*-
from django.db import models

class A(models.Model):
    name = models.CharField(max_length=100)
    class Meta:
        verbose_name = u"A等级"
        verbose_name_plural = verbose_name
        def __str__(self):
            return self.name
class B(models.Model):
    name = models.CharField(max_length=100)
    a    = models.ForeignKey(A,blank=True,null=True,on_delete=models.SET_NULL )
    text = models.TextField(blank=True,verbose_name="测试")
    class Meta:
        verbose_name = u"B等级"
        verbose_name_plural = verbose_name

存储光交管理系统/manager/san/models.py
# -*- coding: utf-8 -*-
from django.db import models
# from storagedata.models import STHOST,STPORT
# Create your models here.
#主机

import django.utils.timezone as timezone
class Jifang(models.Model):
    dress = models.CharField(max_length=100,verbose_name="机房位置", null=True, blank=True)
    def __str__(self):
        name = self.dress
        return name
    class Meta:
        verbose_name = "机房地点"
        verbose_name_plural = verbose_name
class San(models.Model):
    STATUS_CHOICES =(
        ("T","telnet"),
        ("S","ssh"),
        ("C","console"),
        ("M","远程桌面")
    )
    prodname = models.CharField(max_length=20,verbose_name="厂商",blank=True)
    prodect = models.CharField(max_length=30,verbose_name="产品型号",blank=True)
    sn = models.CharField(max_length=40,verbose_name="设备SN",blank=True)
    ip = models.GenericIPAddressField(default="0.0.0.0",verbose_name="管理")
    user = models.CharField(max_length=100,verbose_name="用户名",blank=True)
    password = models.CharField(max_length=100,verbose_name="密码",blank=True)
    renote = models.CharField(max_length=10,verbose_name="远程方式",blank=True,choices=STATUS_CHOICES)
    hardware = models.CharField(max_length=100,verbose_name="硬件信息",blank=True)
    domain = models.CharField(max_length=100,verbose_name="domain",blank=True)
    firmware = models.CharField(max_length=100,verbose_name="固件",blank=True)
    position =models.CharField(max_length=100,verbose_name="设备位置",blank=True)
    jifangadress =models.ForeignKey(Jifang,verbose_name="机房位置",blank=True,null=True,on_delete=models.SET_NULL)
    starttime = models.DateTimeField(verbose_name="启用时间",blank=True,default = timezone.now)
    endtime = models.DateTimeField(verbose_name="过期时间",blank=True,default = timezone.now)
    availableport = models.CharField(max_length=10, verbose_name="可用端口", blank=True)
    nomodelport = models.CharField(max_length=10, verbose_name="无模块端口", blank=True)
    onlineport =  models.CharField(max_length=10, verbose_name="在线端口", blank=True)
    otherport = models.CharField(max_length=10, verbose_name="其他端口", blank=True)
    Notes = models.CharField(max_length=100, verbose_name="备注", blank=True)
    updatetime = models.DateTimeField(verbose_name="更新时间", blank=True,null=True)
    def __str__(self):
        return self.ip
    class Meta:
        verbose_name = "光交清单"
        verbose_name_plural = verbose_name
class Host(models.Model):
    prodname = models.CharField(max_length=20,verbose_name="厂商",blank=True)
    ip = models.GenericIPAddressField(default="0.0.0.0",verbose_name="IP地址")
    hostname = models.CharField(max_length=30,verbose_name="所属部门",blank=True)
    app = models.CharField(max_length=100,verbose_name="业务系统",blank=True)
    apptype = models.CharField(max_length=100,verbose_name="业务类型",blank=True)
    prodect = models.CharField(max_length=30,verbose_name="产品型号",blank=True)
    sn = models.CharField(max_length=40,verbose_name="产品sn",blank=True)
    position =models.CharField(max_length=100,verbose_name="设备位置",blank=True)
    jifangdress = models.ForeignKey(Jifang,verbose_name="机房地点",null=True,blank=True,on_delete=models.SET_NULL)
    def __str__(self):
        return self.ip
    class Meta:
        verbose_name = "主机信息表"
        verbose_name_plural = verbose_name
class Storage(models.Model):
    STATUS_CHOICES =(
        ("T","telnet"),
        ("S","ssh"),
        ("C","console"),
        ("M","远程桌面")
    )
    ST_prodname = models.CharField(max_length=20,verbose_name="厂商",blank=True)
    ST_prodect = models.CharField(max_length=30,verbose_name="产品型号",blank=True)
    ST_sn = models.CharField(max_length=40,verbose_name="设备SN",blank=True)
    ST_ip = models.GenericIPAddressField(default="0.0.0.0",verbose_name="管理")
    ST_user = models.CharField(max_length=100,verbose_name="用户名",blank=True)
    ST_password = models.CharField(max_length=100,verbose_name="密码",blank=True)
    ST_renote = models.CharField(max_length=10,verbose_name="远程方式",blank=True,choices=STATUS_CHOICES)
    ST_hardware = models.CharField(max_length=100,verbose_name="硬件信息",blank=True)
    ST_firmware = models.CharField(max_length=100,verbose_name="固件",blank=True)
    ST_position =models.CharField(max_length=100,verbose_name="设备位置",blank=True)
    STjifang_adress=models.ForeignKey(Jifang,verbose_name="机房位置",blank=True,null=True,on_delete=models.SET_NULL)
    ST_starttime = models.DateTimeField(verbose_name="启用时间",blank=True,null=True)
    ST_endtime = models.DateTimeField(verbose_name="过期时间",blank=True,null=True)
    ST_totalrawcap = models.CharField(max_length=10,verbose_name="裸容量(TB)",blank=True)
    ST_usecap = models.CharField(max_length=20,verbose_name="已使用容量(GB)",blank=True)
    ST_availcap = models.CharField(max_length=10,verbose_name="可用容量(GB)",blank=True)
    ST_totalcap = models.CharField(max_length=10,verbose_name="总容量(可用GB)",blank=True)
    ST_updatetime = models.DateTimeField(verbose_name="更新时间", blank=True, null=True)
    def __str__(self):
        name = self.ST_ip + "(" + self.ST_sn + ")"
        return name
    class Meta:
        verbose_name = "存储清单"
        verbose_name_plural = verbose_name
#光交
class Alias(models.Model):
    pass
class Zone(models.Model):
    pass
class Sanport(models.Model):
    index = models.IntegerField(blank=True,verbose_name="端口",null=True)
    slot = models.IntegerField(blank=True,verbose_name="槽位",null=True)
    port = models.IntegerField(blank=True,verbose_name="槽位端口",null=True)
    speed = models.CharField(max_length=20, blank=True,verbose_name="状态",null=True)
    type = models.CharField(max_length=10, blank=True,verbose_name="类型",null=True)
    fcid = models.CharField(max_length=10, blank=True,verbose_name="fcid",null=True)
    tx = models.CharField(max_length=10, blank=True,verbose_name="发送流量MB",null=True)
    rx = models.CharField(max_length=10, blank=True,verbose_name="接收流量MB",null=True)
    enc_in = models.CharField(max_length=10, blank=True,null=True)
    crc_err = models.CharField(max_length=10, blank=True,verbose_name="数据帧",null=True)
    crc_g_eof = models.CharField(max_length=10, blank=True,null=True)
    two_shrt = models.CharField(max_length=10, blank=True,null=True)
    two_long = models.CharField(max_length=10, blank=True,null=True)
    bad_eof = models.CharField(max_length=10, blank=True,null=True)
    enc_out = models.CharField(max_length=10, blank=True,verbose_name="帧外编码",null=True)
    disc_c3 = models.CharField(max_length=10, blank=True,null=True)
    link_fail = models.CharField(max_length=10, blank=True,null=True)
    loss_sync = models.CharField(max_length=10, blank=True,null=True)
    loss_sig = models.CharField(max_length=10, blank=True,null=True)
    frjt = models.CharField(max_length=10, blank=True,null=True)
    fbsy = models.CharField(max_length=10, blank=True,null=True)
    timeout_tx = models.CharField(max_length=20, blank=True,null=True)
    timeout_rx = models.CharField(max_length=10, blank=True,null=True)
    RX_Power = models.CharField(max_length=10,blank=True,verbose_name="接收光信号",null=True)
    TX_Power = models.CharField(max_length=10, blank=True,verbose_name="发送光信号",null=True)
    Notes = models.CharField(max_length=200, blank=True,verbose_name="备注",null=True)
    san= models.ForeignKey(San,verbose_name="光交",blank=True,null=True,on_delete=models.SET_NULL)
    def __str__(self):
        return "光交%s"%(self.index)
    class Meta:
        verbose_name = "光交端口信息表"
        verbose_name_plural = verbose_name

class Wwn(models.Model):
    from storagedata.models import STPORT,STHOST
    wwn = models.CharField(max_length=32,verbose_name="wwn",unique=True)
    host_wwn = models.ForeignKey(Host,verbose_name="主机",blank=True,null=True,on_delete=models.SET_NULL)
    Sanport_wwn = models.ForeignKey(Sanport,verbose_name="光交端口",blank=True,null=True,on_delete=models.SET_NULL)
    storage_wwn = models.ForeignKey(Storage,verbose_name="存储",blank=True,null=True,on_delete=models.SET_NULL)
    # storageport_wwn = models.OneToOneField(StoragePort, verbose_name="存储端口", blank=True, null=True, on_delete=models.SET_NULL)
    # hostgroup_wwn = models.ManyToManyField(Storagehost, verbose_name="存储host主机", blank=True)
    wwnname = models.CharField(max_length=128,verbose_name="wwn名称",blank=True,null=True)
    STport= models.OneToOneField(STPORT, verbose_name="SR存储端口", blank=True, null=True, on_delete=models.SET_NULL)
    SThost = models.ManyToManyField(STHOST, verbose_name="ST存储host主机", blank=True)
    def __str__(self):
        return self.wwn
    class Meta:
        verbose_name = "wwn信息表"
        verbose_name_plural = verbose_name
class Errlog(models.Model):
    STATUS_CHOICES =(
        ("Y",u"是"),
        ("N",u"否"),
    )
    elog = models.CharField(max_length=300,verbose_name="错误日志",blank=True)
    etime = models.DateTimeField(auto_now_add=True,verbose_name="报错时间",blank=True,null=True)
    affirm = models.CharField(max_length=10,verbose_name="是否已确认",choices=STATUS_CHOICES,blank=True)
    grade = models.IntegerField(verbose_name="告警等级",blank=True,default="4")
    def __str__(self):
        return "告警"
    class Meta:
        verbose_name = u"告警"
        verbose_name_plural = verbose_name
class Doment(models.Model):
    text = models.TextField(blank=True)
    storage = models.ForeignKey(Storage,verbose_name="存储信息",null=True,blank=True,on_delete=models.SET_NULL)
    san = models.ForeignKey(San,verbose_name="光交信息",null=True,blank=True,on_delete=models.SET_NULL)
    dotime = models.DateTimeField(verbose_name="添加时间",blank=True)
    class Meta:
        verbose_name = "日志"
        verbose_name_plural = verbose_name

class Sanlog_clean(models.Model):
    San_portid = models.ForeignKey(Sanport,verbose_name="端口清洗",null=True,blank=True,on_delete=models.SET_NULL)
    San_log = models.ForeignKey(Doment,verbose_name="log日志清洗",null=True,blank=True,on_delete=models.SET_NULL)
    San_wwn = models.CharField(max_length=32,verbose_name="wwn",null=True,blank=True)
    enc_in = models.CharField(max_length=10, blank=True,null=True)

存储光交管理系统/manager/ceshi/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from ceshi import models
# Create your views here.
def index(requests):
    return render(requests,"ceshi.html",locals())
def search(requests):
    return HttpResponse("oks")
def search1(requests):
    return HttpResponse("oks1111")
def fenye(requests):
    obj = models.B.objects.all()
    if not requests.GET.get("page"):
        page = 1
    else:
        page = requests.GET.get("page")
    paginator = Paginator(obj,2)
    contacts = paginator.page(page)
    return render(request,"fenye.html",{"contacts":contacts})


def Testtubiao(request):
    return render(request,"test.html")

存储光交管理系统/manager/templates/addhost.html
{% extends "nav.html" %}
{% block little %}存储-添加主机{% endblock %}
{% block content %}
    <!-- Main Content -->
    <div class="container-fluid">
        <div class="side-body">
            <div class="page-title">
                <span class="title">主机</span>
                <div class="description">主机添加</div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">
                                <div class="title">{{ little }}批量添加</div>
                                <div class="row">
                                    <div class="col-sm-10"><input type="file" id="exampleInputFile"></div>
                                    <div class="col-sm-1" style="margin-top:-5px"><button type="button" class="btn btn-default btn-xs">上   传</button><p class="help-block"></div>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <table id = "add_tablist"class="datatable table table-striped" cellspacing="0" width="100%">
                                <tbody>
                                <tr>
                                    <td width="100"><input type="text" class="form-control" placeholder="厂商" id="prodname"/></td>
                                    <td width="100"><input type="text" class="form-control" placeholder="主机型号"id ="prodect"/></td>
                                    <td width="100"><input type="text" class="form-control" placeholder="主机SN"id ="sn"/></td>
                                    <td width="150"><input type="text" class="form-control" placeholder="主机IP,必填项" id="ip"/></td>
                                    <td width="100"><input type="text" class="form-control" placeholder="所属部门" id="hostname"/></td>
                                    <td width="100"><input type="text" class="form-control" placeholder="业务系统" id="app"/></td>
                                    <td width="100"><input type="text" class="form-control" placeholder="业务类型" id="apptype"/></td>
                                    <td width="100"><input type="text" class="form-control" placeholder="主机位置" id="position"/></td>
                                    <td><input type="text" class="form-control" placeholder="主机wwn,存在多个wwn请用空格隔开" id="wwn"/></td>
                                </tr>
                                </tbody>
                            </table>
                            <a type="button" class="btn btn-default" id = "add_host">添 加 一 行</a>
                            <a type="button" class="btn btn-default" id="del_list">删 除 一 行</a>
                            <a type="button" class="btn btn-default"id = "clear_list">全 部 清 除</a>
                            <a type="button" class="btn  btn-success" style="" id="save_list">保 存</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block js %}
    <div class="modal fade" tabindex="-1" role="dialog" id="host_update">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">添加主机</h4>
                </div>
                <div class="modal-body">
                    <p id="host_err">添加中，请稍候</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default st_close" data-dismiss="modal">关 闭</button>
                    {#                    <button type="button" class="btn btn-primary">Save changes</button>#}
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <script>
        var count = 1
        $("#add_host").click(function () {
            console.log("ok")
            var data = $("tbody tr:first").clone()
            $("tbody").append(data)
            count++
            $("#host_count").text(count)
        });
        $("#del_list").click(function () {
            $("tbody tr:last").remove()
            count--
            $("#host_count").text(count)
        });
        $("#clear_list").click(function () {
            location.reload();
            $("#prodname").val("");
            $("#prodect").val("");
            $("#ip").val("");
            $("#hostname").val("");
            $("#sn").val("");
            $("#app").val("");
            $("#apptype").val("");
            $("#position").val("");
            $("#wwn").val("");

        });
        $("#save_list").click(function () {
            $("#host_update").modal('toggle')
            var countnum = 0
            var obj = {}
            $("#add_tablist tbody tr").each(function () {
                countnum++;
                var prodname = $(this).children().find("#prodname").val();
                var prodect = $(this).children().find("#prodect").val();
                var ip = $(this).children().find("#ip").val();
                var hostname = $(this).children().find("#hostname").val();
                var sn = $(this).children().find("#sn").val();
                var app = $(this).children().find("#app").val();
                var apptype = $(this).children().find("#apptype").val();
                var position = $(this).children().find("#position").val();
                var wwn = $(this).children().find("#wwn").val();
                obj[countnum] ={prodname:prodname,prodect:prodect,ip:ip.trim(),hostname:hostname,sn:sn,app:app,apptype:apptype,position:position,wwn:wwn.trim()};
            })
            console.log(obj)
            $.ajax({
                url: "{% url "addhost_ajax" %}",
                type: 'POST',
                data:{data:JSON.stringify(obj)},
                success: function(data){
                    var obj = JSON.parse(data);
                    if(obj.status){
                        $("#host_err").text("添加成功");
                        location.reload();
                    }else{
                        $("#host_err").text(obj["error"]);
                    };
                }
            });
        });
    </script>
{% endblock %}

存储光交管理系统/manager/templates/log_xijie.html
{% extends "nav.html" %}
{% block little %}存储光交日志{% endblock %}
{% block content %}
    <!-- Main Content -->
    <div class="container-fluid">
        <div class="side-body">
            <div class="page-title">
                <span class="title">详细日志</span>
                <div class="description"}>日志查看</div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <!-- 框内详细内容-->
                            {% for i in data %}
                                <div>
                                    <textarea class="form-control" rows="3"style="height:400px;">{{ i.text }}</textarea>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block js %}{% endblock %}

存储光交管理系统/manager/templates/san_brocade.html
{% extends "nav.html" %}
{% block little %}存储{{ data.first.san }}{% endblock %}
{% block content %}
    <!-- Main Content -->
    <div class="container-fluid">
        <div class="side-body">
            <div class="page-title">
                <span class="title">光交</span>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">
                                <div class="title">光交详细清单</div>
                            </div>
                            <div class="card-body">
                                <table class="datatable table table-striped" cellspacing="0" width="100%">
                                    <thead>
                                    <tr>
                                        <th>虚拟端口</th>
                                        <th>槽位</th>
                                        <th>槽位端口</th>
                                        <th>状态</th>
                                        <th>类型</th>
                                        <th>wwn</th>
                                        <th>数据帧</th>
{#                                        <th>发送流量(mb)</th>#}
{#                                        <th>接收流量(mb)</th>#}
                                        <th>发送光信号</th>
                                        <th>接收光信号</th>
                                        <th>流量</th>
                                        <th>主机IP</th>
                                        <th>业务名称</th>
                                        <th>存储IP</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        {% for i in data%}
                                            <tr>
                                                <td>{{ i.index }}</td>
                                                <td>{{ i.slot }}</td>
                                                <td>{{ i.port }}</td>
                                                <td class="am-hide-sm-only">{{ i.speed }}</td>
                                                <td class="am-hide-sm-only">{{ i.type }}</td>
                                                <td class="am-hide-sm-only">
{#                                                    {% if  i.wwn_set.all|length > 0 %}#}
{#                                                        {% for k in  i.wwn_set.all  %}#}
{#                                                            <p>{{ k.wwn }}</p>#}
{#                                                        {% endfor %}#}
{#                                                    {% endif %}#}
                                                    {{ i.wwn__wwn }}
                                                </td>
                                                <td class="am-hide-sm-only">{{ i.crc_err }}</td>
{#                                                <td class="am-hide-sm-only">{{ i.tx }}</td>#}
{#                                                <td class="am-hide-sm-only">{{ i.rx }}</td>#}
                                                <td class="am-hide-sm-only">{{ i.TX_Power }}</td>
                                                <td class="am-hide-sm-only">{{ i.RX_Power }}</td>
                                                <td class="am-hide-sm-only">{{ i.rx }}</td>
                                                <td class="am-hide-sm-only">
{#                                                    {% if  i.wwn_set.all|length > 0 %}#}
{#                                                        {% for k in  i.wwn_set.all  %}#}
{#                                                            <p><a >{{ k.host_wwn }}</a></p>#}
{#                                                        {% endfor %}#}
{#                                                    {% endif %}#}
                                                    {{ i.wwn__host_wwn__ip }}
                                                </td>
                                                <td>{{ i.wwn__host_wwn__app }}</td>
                                                <td class="am-hide-sm-only">
{#                                                    {% if  i.wwn_set.all|length > 0 %}#}
{#                                                        {% for k in  i.wwn_set.all  %}#}
{#                                                            <p><a data-toggle="popover" id="san_poper">{{ k.storage_wwn }}</a></p>#}
{#                                                        {% endfor %}#}
{#                                                    {% endif %}#}
                                                    {{ i.wwn__storage_wwn__ST_ip}}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        $(function () {
        })
    </script>
{% endblock %}